language: c

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -q

    # install libtoxav dependencies
  - sudo apt-get install -y libopus-dev libvpx-dev

install:
  - _libsodium_version=1.0.0
  - _weechat_version=v1.0

    # install libsodium (libtoxcore dependency)
  - git clone git://github.com/jedisct1/libsodium.git
  - pushd libsodium
  - git checkout tags/${_libsodium_version}
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j3
  - sudo make install
  - popd

    # install libtoxcore
  - git clone git://github.com/irungentoo/toxcore
  - pushd toxcore
  - autoreconf -i
  - ./configure --prefix=/usr --disable-testing --disable-ntox
  - make -j3
  - sudo make install
  - popd

    # install weechat
  - git clone git://github.com/weechat/weechat
  - pushd weechat
  - git checkout tags/${_weechat_version}
  - mkdir build && cd build
  - cmake .. -DPREFIX=/usr
  - make -j3
  - sudo make install
  - popd

script:
  - mkdir build && cd build
  - cmake ..
  - make -j3

